#!/bin/bash

echo "🔧 CONFIGURAÇÃO URGENTE - VARIÁVEIS VERCEL"
echo "========================================="
echo ""
echo "❌ ERRO PERSISTE: Variables mal configuradas"
echo "✅ SOLUÇÃO: Configurar corretamente no dashboard"
echo ""
echo "📋 PASSOS OBRIGATÓRIOS:"
echo "1. Acesse: https://vercel.com/dashboard"
echo "2. Projeto: padoka-delivery"
echo "3. Settings → Environment Variables"
echo "4. DELETE todas as variáveis existentes"
echo "5. Adicione as 2 variáveis abaixo:"
echo ""
echo "📝 VARIÁVEL 1 (COPIE E COLE):"
echo "Name: VITE_SUPABASE_URL"
echo "Value: https://ywpazjaaqavjcdonlnzs.supabase.co"
echo ""
echo "📝 VARIÁVEL 2 (COPIE E COLE):"
echo "Name: VITE_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3cGF6amFhcWF2amNkb25sbnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NzU2MzcsImV4cCI6MjA3NzQ1MTYzN30.cCFHu1eL0nwZcsOQ29_Yz_-0NwG3noF9dqEsjMrkiOs"
echo ""
echo "6. SAVE ambas"
echo "7. Aguardar deploy automático"
echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "   • Deploy automático (2-3 min)"
echo "   • Build success"
echo "   • App funcionando"