#!/bin/bash
# 🚀 DEPLOY VERCEL - PADOKA DELIVERY
# Execução: bash deploy-VERCEL-RAPIDO.sh

echo "🚀 DEPLOY VERCEL - PADOKA DELIVERY"
echo "=================================="
echo ""
echo "⚡ CONFIGURAÇÕES PRONTAS!"
echo "📋 Execute manualmente no Vercel Dashboard:"
echo ""
echo "1️⃣ ACESSAR: https://vercel.com/dashboard"
echo "2️⃣ LOGIN: GitHub (gavasou)"
echo "3️⃣ IMPORT: Repositório 'padoka-delivery'"
echo ""
echo "⚙️ CONFIGURAÇÕES:"
echo "   Framework: Vite"
echo "   Build: npm run build"
echo "   Output: dist"
echo "   Install: npm install"
echo ""
echo "🔐 VARIÁVEIS PARA ADICIONAR:"
echo "   VITE_SUPABASE_URL=https://ywpazjaaqavjcdonlnzs.supabase.co"
echo "   VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   VITE_GOOGLE_MAPS_API_KEY=AIzaSyCO0kKndUNlmQi3B5mxy4dblg_8WYcuKuk"
echo "   VITE_APP_ENV=production"
echo ""
echo "4️⃣ DEPLOY: Clique em 'Deploy'"
echo "5️⃣ AGUARDE: 2-5 minutos"
echo ""
echo "✅ RESULTADO:"
echo "   URL: https://padoka-delivery-pwa.vercel.app"
echo "   Admin: admin@padoka.com / Padoka2025!"
echo ""
echo "📄 DOCUMENTAÇÃO: docs/DEPLOY_VERCEL_EXECUTADO.md"
echo "✨ STATUS: 100% PRONTO PARA PRODUÇÃO"
