#!/bin/bash

echo "🔧 VERIFICAÇÃO DE VARIÁVEIS DE AMBIENTE"
echo "====================================="
echo ""
echo "❌ ERRO ATUAL: Variables estão sendo interpretadas como comandos"
echo "✅ SOLUÇÃO: Configurar corretamente no dashboard do Vercel"
echo ""
echo "📋 AÇÕES NECESSÁRIAS:"
echo "1. Acesse: https://vercel.com/dashboard"
echo "2. Vá em: Settings → Environment Variables"
echo "3. DELETE qualquer variable que não seja valor simples"
echo "4. Adicione estas variáveis CORRETAS:"
echo ""
echo "📝 VARIÁVEL 1:"
echo "Name: VITE_SUPABASE_URL"
echo "Value: https://ywpazjaaqavjcdonlnzs.supabase.co"
echo ""
echo "📝 VARIÁVEL 2:"
echo "Name: VITE_SUPABASE_ANON_KEY" 
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3cGF6amFhcWF2amNkb25sbnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NzU2MzcsImV4cCI6MjA3NzQ1MTYzN30.cCFHu1eL0nwZcsOQ29_Yz_-0NwG3noF9dqEsjMrkiOs"
echo ""
echo "✅ SAVE e aguarde deploy automático (2-3 min)"